# You must accept the Chef License to use this software: https://www.chef.io/end-user-license-agreement/
# Change [chef_license] from acceptance = "undefined" to acceptance = "accept-no-persist" if you agree to the license.

interval = 10
splay = 1
splay_first_run = 0
run_lock_timeout = 1800
log_level = "warn"
env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ssl_verify_mode = ":verify_peer"

[chef_license]
acceptance = "accept-no-persist"

[automate]
enable = false
server_url = "https://<automate_url>"
token = "<automate_token>"